export const GET_PRODUCT_STOCK_REQUEST = "GET_PRODUCT_STOCK_REQUEST";
export const GET_PRODUCT_STOCK_SUCCESS = "GET_PRODUCT_STOCK_SUCCESS";
export const GET_PRODUCT_STOCK_FAIL = "GET_PRODUCT_STOCK_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";